version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Syncs code changes to the container
      - /app/node_modules  # Avoids overwriting node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]  # Use a dev script for hot-reloading
